# Generated by Django 4.0.10 on 2024-06-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('schedule', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('slots_remaining', models.DecimalField(decimal_places=0, default=15, max_digits=2)),
            ],
        ),
    ]
