# Generated by Django 4.0.10 on 2024-07-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_user_alter_class_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
