# Generated by Django 4.0.10 on 2024-08-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone_number'),
        ('classes', '0003_class_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='student_list',
            field=models.ManyToManyField(related_name='register_classes', to='users.user'),
        ),
    ]
