# Generated by Django 4.0.10 on 2024-08-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_student_list'),
        ('users', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_classes',
            field=models.ManyToManyField(related_name='students', to='classes.class'),
        ),
    ]
